[package]
name = "sample7-framebuffer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27"
env_logger = "0.9"
log = "0.4"
wgpu = "0.17"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
glam = "0.22"
image = { version = "0.24", features = [ "png", "jpeg" ] }
